<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.smartlibrary.setznagl</groupId>
    <artifactId>my-beloved-smart-library</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>MyBelovedSmartLibrary</name>

    <profiles>
            <profile>
                <id>dev</id>
                <properties>
                    <project.java.version>17</project.java.version>
                    <project.java.vendor>Amazon Corretto</project.java.vendor>
                </properties>
                <activation>
                    <os>
                        <family>Linux</family>
                        <name>Ubuntu</name>
                        <version>latest</version>
                    </os>
                    <jdk>17</jdk>
                    <activeByDefault>true</activeByDefault>
                </activation>
            </profile>
            <profile>
                <id>prod</id>
                <properties>
                    <project.java.version>17</project.java.version>
                    <project.java.vendor>Amazon Corretto</project.java.vendor>
                </properties>
                <activation>
                    <os>
                        <family>Linux</family>
                        <name>Ubuntu</name>
                        <version>latest</version>
                    </os>
                    <jdk>17</jdk>
                    <activeByDefault>false</activeByDefault>
                </activation>
            </profile>
    </profiles>

    <modules>
        <!-- <module>src/core/controller/src</module> -->
        <!--  <module>Application/core/dao/src</module> -->
       <module>Application/core/model/src</module>
        <!-- <module>Application/core/repository/src</module> -->
        <!-- <module>src/core/resources/src</module> -->
        <!-- <module>src/core/services/src</module> -->
        <!-- <module>src/core/util/src</module> -->
        <!-- <module>Application/core/web/src </module> -->
   </modules>

   <properties>
       <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
       <maven.compiler.source>17</maven.compiler.source>
       <maven.compiler.target>17</maven.compiler.target>
       <junit.version>5.10.0</junit.version>
   </properties>

   <dependencies>
       <!-- -->
   </dependencies>

</project>